apps/washmachine/urls.py
#!usr/bin/python
# -*- coding:utf-8 _*-
from django.conf.urls import url

from apps.washmachine import views

urlpatterns = [

    url(r'^$', views.view_washmachine, name="view_washmachine"),
    url(r'^add/$', views.add_washmachine, name='add_washmachine'),
    url(r'^remove/(?P<id>\d+)/$', views.remove_washmachine, name='remove_washmachine'),
    url(r'^modify/$', views.modify_washmachine, name='modify_washmachine'),
    url(r'^findOne/(?P<id>\d+)/$', views.findOne_washmachine, name='findOne_washmachine'),
    url(r'^findAllOfCondition/$', views.findAllOfCondition_washmachine, name='findAllOfCondition_washmachine'),
    url(r'^washmachineForm/$', views.view_washmachineForm, name='view_washmachineForm'),
    url(r'^findOne/(?P<id>\d+)/$', views.findOne_washmachine, name='findOne_washmachine'),
    url(r'^use/(?P<id>\d+)/$', views.use_washmachine, name='use_washmachine'),

]

swm/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^account/', include('apps.account.urls')),
    url(r'^', include('apps.account.urls')),
    url(r'^student/', include('apps.student.urls')),
    url(r'^repair/', include('apps.repair.urls')),
    url(r'^washmachine/', include('apps.washmachine.urls')),
    url(r'^appointment/', include('apps.appointment.urls')),
    url(r'^money/', include('apps.money.urls')),
    url(r'^repairment/', include('apps.repairment.urls')),

]
#
# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

apps/repairment/models.py
from django.db import models


# Create your models here.

class Repairment(models.Model):
    STATE_CHOICES = (
        ('R', '报修中'),
        ('W', '待清洗'),
        ('E', '已完成'),
        ('C', '已取消'),
    )
    machine_id = models.CharField('洗衣机编号', max_length=10)
    repair_account = models.CharField('提交异常账号', max_length=30)
    repair_time = models.DateTimeField('提交异常时间', auto_now_add=True)
    complete_account = models.CharField('处理异常账号', max_length=30, null=True)
    complete_time = models.DateTimeField('处理异常时间', null=True)
    remarks = models.CharField('备注', max_length=300, null=True)
    state = models.CharField('处理异常状态', max_length=1, choices=STATE_CHOICES)

    class Meta:
        db_table = 'repairment'
        permissions = (
            ("view_repairment", "Can view the repairment"),
            ("findOne_repairment", "Can find a repairment"),
            ("findAllOfCondition_repairment", "Can find all repairments of condition"),
            ("view_repairmentForm", "Can view the repairment form"),
            ("complete_repairment", "Can be sure that complete the repairment"),
            ("cancel_repairment", "Can cancel the repairment")
        )

    def __str__(self):
        return self.machine_id

apps/washmachine/models.py
from django.db import models


# Create your models here.

class WashMachine(models.Model):
    STATE_CHOICES = (
        ('F', '空闲'),
        ('W', '工作中'),
        ('B', ' 故障'),
        ('D', '待清洗'),
        ('A', '预约中')
    )
    machine_id = models.CharField('洗衣机编号', max_length=10)
    dormitory_building_number = models.IntegerField('寝室楼号')
    account = models.CharField('使用账号', max_length=30, null=True)
    start_time = models.DateTimeField('工作起始时间', null=True)
    end_time = models.DateTimeField('工作结束时间', null=True)
    state = models.CharField('运行状态', max_length=1, choices=STATE_CHOICES)

    class Meta:
        db_table = 'washmachine'
        permissions = (
            ("view_washmachine", "Can view the washmachine"),
            ("remove_washmachine", "Can remove a washmachine"),
            ("modify_washmachine", "Can modify a washmachine"),
            ("findOne_washmachine", "Can find a washmachine"),
            ("findAllOfCondition_washmachine", "Can find all washmachines of condition"),
            ("view_washmachineForm", "Can view the washmachine form"),
            ("use_washmachine", "Can use the washmachine")

        )

    def __str__(self):
        return self.machine_id

apps/washmachine/forms.py
#!usr/bin/python
#-*- coding:utf-8 _*- 

apps/washmachine/views.py
import decimal
import json
import time

import datetime
from apscheduler.schedulers.background import BackgroundScheduler
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from apps.appointment.models import Appointment
from apps.appointment.tasks import washmachine_task
from apps.money.models import Money
from apps.student.models import StudentInformation
from apps.washmachine.models import WashMachine
from utils.ResponseBean import ResponseBean


@permission_required('washmachine.add_washmachine')
@login_required
@csrf_exempt
def add_washmachine(request):
    if request.method == 'POST':
        d = json.loads(str(request.body, encoding="utf-8"))
        machine_id = d['machine_id']
        dormitory_building_number = d['dormitory_building_number']
        state = 'F'
        new_washmachine = WashMachine.objects.create(machine_id=machine_id,
                                                     dormitory_building_number=dormitory_building_number,
                                                     state=state)
        new_washmachine.save()
        response = ResponseBean().get_success_instance()
        response.message = '新建洗衣机成功。'
        print(json.dumps(response.__dict__))
        return JsonResponse(response.__dict__)


@permission_required('washmachine.remove_washmachine')
@login_required
@csrf_exempt
def remove_washmachine(request, id):
    washmachine = get_object_or_404(WashMachine, id=id)
    washmachine.delete()
    response = ResponseBean().get_success_instance()
    response.message = '删除洗衣机成功。'
    return JsonResponse(response.__dict__)


@permission_required('washmachine.modify_washmachine')
@login_required
@csrf_exempt
def modify_washmachine(request):
    if request.method == 'POST':
        d = json.loads(str(request.body, encoding="utf-8"))
        washmachine = get_object_or_404(WashMachine, id=d['id'])
        if 'machine_id' in d.keys():
            washmachine.machine_id = d['machine_id']
        if 'dormitory_building_number' in d.keys():
            washmachine.dormitory_building_number = d['dormitory_building_number']
        if 'state' in d.keys():
            washmachine.state = d['state']
        washmachine.save()
        response = ResponseBean().get_success_instance()
        response.message = '修改洗衣机信息成功。'
        return JsonResponse(response.__dict__)


@permission_required('washmachine.findOne_washmachine')
@login_required
@csrf_exempt
def findOne_washmachine(request, id):
    washmachine = get_object_or_404(WashMachine, id=id)
    washmachine.__dict__.pop('_state')
    response = ResponseBean().get_success_instance()
    response.message = '查询成功。'
    response.data = washmachine.__dict__
    return JsonResponse(response.__dict__)


@permission_required('washmachine.findAllOfCondition_washmachine')
@login_required
@csrf_exempt
def findAllOfCondition_washmachine(request):
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        data = WashMachine.objects.all()
        d = json.loads(str(request.body, encoding="utf-8"))
        if 'machine_id' in d.keys():
            data = data.filter(machine_id=d['machine_id'])
        if 'dormitory_building_number' in d.keys():
            data = data.filter(dormitory_building_number=d['dormitory_building_number'])
        if 'state' in d.keys():
            data = data.filter(state=d['state'])
        if 'page_index' in d.keys():
            page_index = d['page_index']
        else:
            page_index = 1
        if 'page_size' in d.keys():
            page_size = d['page_size']
        else:
            page_size = 10

        totol = data.__len__()
        paginator = Paginator(data, page_size)
        try:
            data = paginator.page(page_index)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        response = ResponseBean().get_success_instance()
        response.message = "查询成功。"
        response.total = totol
        response.used = False
        data_list = []
        for element in data:
            element.is_me = False
            if element.state == 'A':
                appointment = get_object_or_404(Appointment, machine_id=element.machine_id, state='A')
                element.start_time = appointment.start_time
                element.end_time = appointment.end_time
                if appointment.account == user.username:
                    element.is_me = True
                    response.used = True
            elif element.state == 'W':
                if element.account == user.username:
                    element.is_me = True
                    response.used = True
            if element.start_time:
                element.start_time = time.mktime(element.start_time.timetuple()) * 1000
            if element.end_time:
                element.end_time = time.mktime(element.end_time.timetuple()) * 1000
            element.__dict__.pop('_state')
            data_list.append(element.__dict__)
        response.data = data_list
        return JsonResponse(response.__dict__)


@permission_required('washmachine.view_washmachine')
@login_required
def view_washmachine(request):
    return render(request,
                  'washmachine/washmachine.html')


@permission_required('washmachine.view_washmachineForm')
@login_required
def view_washmachineForm(request):
    return render(request,
                  'washmachine/washmachineForm.html')


@permission_required('washmachine.use_washmachine')
@login_required
@csrf_exempt
def use_washmachine(request, id):
    scheduler = BackgroundScheduler()
    washmachine = get_object_or_404(WashMachine, id=id)
    user = User.objects.get(id=request.user.id)
    student = get_object_or_404(StudentInformation, user=user)
    if student.balance < 5:
        msg = '余额不足，请充值。'
    else:
        machine_id = washmachine.machine_id
        start_time = datetime.datetime.now()
        end_time = start_time + datetime.timedelta(seconds=+45)
        washmachine.start_time = start_time
        washmachine.end_time = end_time
        washmachine.account = user.username
        trading_account = user.username
        trading_amount = decimal.Decimal('-5.00')
        student.balance = student.balance + trading_amount
        balance = student.balance
        transaction_type = 'P'
        new_money = Money.objects.create(trading_account=trading_account,
                                         trading_amount=trading_amount,
                                         balance=balance,
                                         transaction_type=transaction_type)
        washmachine.state = 'W'
        appointment = get_object_or_404(Appointment, machine_id=machine_id, state='A')
        appointment.state = 'E'
        student.save()
        new_money.save()
        washmachine.save()
        appointment.save()
        scheduler.add_job(washmachine_task, 'date', run_date=end_time)
        scheduler.start()
        msg = '开始使用洗衣机，将在45分钟之后结束工作。'
    response = ResponseBean().get_success_instance()
    response.message = msg
    return JsonResponse(response.__dict__)

templates/washmachine/washmachine.html
{% extends "base.html" %}
{% load static %}
{% block title %}Wash Machine Manage{% endblock %}
{% block content %}
    <div class="admin-main">
        <blockquote class="layui-elem-quote">
            {% if perms.washmachine.view_washmachineForm and perms.washmachine.add_washmachine %}
                <a href="javascript:void(0);" class="layui-btn layui-btn-sm" id="add">
                    <i class="fa fa-plus-circle"></i> 新建
                </a>
            {% endif %}
            <a href="javascript:void(0);" class="layui-btn layui-btn-sm" id="reload">
                <i class="fa fa-repeat"></i> 刷新重置
            </a>
        </blockquote>
        <div class=" layui-form">
            <table class="layui-table admin-table">
                <thead>
                <tr>
                    <th style="width: 30px;"><input type="checkbox" lay-filter="allselector" lay-skin="primary"
                                                    title=""></th>
                    <th>洗衣机编号</th>
                    <th>寝室楼号</th>
                    <th>运行状态</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody id="table_content">
                </tbody>
            </table>
        </div>
        <div class="placepass"></div>
        <div class="admin-table-page">
            <div id="paged" class="page"></div>
        </div>
    </div>
{% endblock %}
{% block templates_script %}
    <script src="{% static 'js/washmachine/washmachine.js' %}"></script>
    <script type="text/html" id="tpl">
        <%# layui.each(d.data, function(index, item){ %>
        <tr data-id="<% item.id %>" data-endtime="<% item.end_time %>">
            <td><input type="checkbox" lay-skin="primary" title=""></td>
            <td><% item.machine_id?item.machine_id:"-" %></td>
            <td><% item.dormitory_building_number?item.dormitory_building_number:"-" %></td>
            <td>
                <%# if(!item.state){ %>
                -
                <%# }%>
                <%# if(item.state==='F'){ %>
                空闲
                <%# }%>
                <%# if(item.state==='W'){ %>
                工作中 <span id="T<% item.id %>"></span>
                <%# }%>
                <%# if(item.state==='A'){ %>
                预约中 <span id="T<% item.id %>"></span>
                <%# }%>
                <%# if(item.state==='B'){ %>
                <span style="color:red;">故障</span>
                <%# }%>
                <%# if(item.state==='D'){ %>
                <span style="color:red;">待清洁</span>
                <%# }%>
            </td>
            <td>
                {% if perms.washmachine.findOne_washmachine %}
                    <a href="javascript:void(0);" data-opt="details"
                       class="layui-btn layui-btn-normal layui-btn-xs">详情</a>
                {% endif %}
                {% if perms.appointment.add_appointment %}
                    <%# if(item.state==='F'&&d.used===false){ %>
                    <a href="javascript:void(0);" data-opt="appointment"
                       class="layui-btn layui-btn-xs">预约</a>
                    <%# }%>
                {% endif %}
                {% if perms.washmachine.use_washmachine %}
                    <%# if(item.state==='A'&&item.is_me===true){ %>
                    <a href="javascript:void(0);" data-opt="use"
                       class="layui-btn layui-btn-xs">使用</a>
                    <%# }%>
                {% endif %}
                {% if perms.repairment.view_repairmentForm and perms.repairment.add_repairment %}
                    <%# if(item.state!=='B'&&item.state!=='D'){ %>
                    <a href="javascript:void(0);" data-opt="addRepairment"
                       class="layui-btn layui-btn-warm layui-btn-xs">提交异常</a>
                    <%# }%>
                {% endif %}
                {% if perms.washmachine.view_washmachineForm and perms.washmachine.modify_washmachine %}
                    <a href="javascript:void(0);" data-opt="edit" class="layui-btn layui-btn-xs">编辑</a>
                {% endif %}
                {% if perms.washmachine.remove_washmachine %}
                    <a href="javascript:void(0);" data-opt="delete"
                       class="layui-btn layui-btn-danger layui-btn-xs">删除</a>
                {% endif %}
            </td>
        </tr>
        <%# }); %>
    </script>
{% endblock %}

templates/washmachine/washmachineForm.html
<div style="margin: 15px;">
    <form class="layui-form" id="washmachine">
        <div class="layui-form-item">
            <label class="layui-form-label label-width">洗衣机编号</label>
            <div class="layui-input-inline">
                <input type="text" name="machine_id" required lay-verify="required" placeholder="请输入洗衣机编号"
                       autocomplete="off" class="layui-input" v-model="machine_id">
            </div>
            <div class="layui-form-mid layui-word-aux" style="color: red">*</div>
        </div>
        <div class="layui-form-item">
            <label class="layui-form-label label-width">寝室楼号</label>
            <div class="layui-input-inline">
                <input type="number" name="dormitory_building_number" required lay-verify="required"
                       placeholder="请输入寝室楼号" autocomplete="off" class="layui-input" v-model="dormitory_building_number">
            </div>
            <div class="layui-form-mid layui-word-aux" style="color: red">*</div>
        </div>
        <button lay-filter="edit" lay-submit style="display: none;"></button>
    </form>
</div>